### ISSUE TITLE
Coming back to life after pause not working

### ISSUE THREAD

**Issue by flxapps** [flxapps/DetoxDroid#39] opened 2021-07-20 08:57 UTC
Submitter: Marco
Oneplus 7 OOS11 stock rom
Enabled pause (1 min) in quicksettings for the black and white mode but after 1 min the colors don't change. 
after I open detox Droid it works again

**Comment by jnnkB** [comment] 2021-09-21 08:00
I have this issue too. If you need any more information for debugging I'm happy to help.

**Comment by jnnkB** [comment] 2021-09-21 08:01
Duplicate of #38

**Closed** 2024-01-17 10:31 UTC
Labels: bug
